import http from 'node:http'
import { readFile } from 'node:fs/promises'
import { createServer } from 'vite'
const vite = await createServer({
  server: { middlewareMode: true },
  appType: 'custom',
})
const server = http.createServer((req, res) => {
  vite.middlewares(req, res, async (error) => {
    if (error) {
      res.statusCode = 500
      res.end('Development server error')
      return
    }
    try {
      if (req.url.split('?')[0] === '/feed.xml') {
        res.statusCode = 404
        res.end('RSS is generated by npm run build')
        return
      }
      const template = await vite.transformIndexHtml(
        req.url,
        await readFile('index.html', 'utf8'),
      )
      const { render } = await vite.ssrLoadModule('/src/entry-server.jsx')
      const page = render(req.url)
      res.writeHead(page.status, { 'Content-Type': 'text/html; charset=utf-8' })
      res.end(
        template
          .replace('<!--page-head-->', page.head)
          .replace('<!--app-html-->', page.html),
      )
    } catch (e) {
      vite.ssrFixStacktrace(e)
      console.error(e)
      res.statusCode = 500
      res.end('Development build failed. See the terminal for details.')
    }
  })
})
server.listen(5173, '127.0.0.1', () =>
  console.log('SMA development: http://127.0.0.1:5173/'),
)
for (const signal of ['SIGINT', 'SIGTERM'])
  process.on(signal, async () => {
    await vite.close()
    server.close()
    process.exit(0)
  })
